language: node_js
node_js:
  - "8"
dist: trusty
sudo: required

env:
  global:
    - DISPLAY=:99

before_install:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - tools/travis/bxsetup.sh
  - export PATH=$TRAVIS_BUILD_DIR/IBM\ Cloud\ Functions\ Shell-linux-x64/:$PATH

install:
  - tools/travis/install.sh

script:
  - fsh plugin list