language: node_js
node_js:
  - "8"
dist: trusty
sudo: required

env:
  global:
    - DISPLAY=:99

before_install:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - tools/travis/bxsetup.sh
  - tools/travis/fshclone.sh
  - export PATH=$TRAVIS_BUILD_DIR/shell/app/bin:$PATH

install:
  - npm install
  - tools/travis/plugininstall.sh

jobs:
  include:
    - stage: tests
      script: npm test
