language: node_js
node_js:
  - "8"
dist: trusty
sudo: required

env:
  global:
    - DISPLAY=:99

before_install:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - tools/travis/bxsetup.sh
  - tools/travis/install.sh

