language: node_js
node_js:
  - "8"
dist: trusty
sudo: required

env:
  global:
    - DISPLAY=:99

before_install:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - export PATH=$TRAVIS_BUILD_DIR/IBM\ Cloud\ Functions\ Shell-linux-x64/:$PATH
  - tools/travis/bxsetup.sh
  - tools/travis/fshinstall.sh

install:
  - npm install

jobs:
  include:
    - stage: e2einstall
      script: ./src/test/e2e/plugininstall.sh
    - stage: tests
      script: npm test
